version: '3.5'
services:
  namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.3.1
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/broker.conf
    volumes:
      - ./broker.conf:/home/rocketmq/broker.conf
    depends_on:
      - namesrv