
server:
  port: 8090

spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_db
    username: root
    password: root
  data:
    redis:
      cluster:
        nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        max-redirects: 5
rocketmq:
  name-server: localhost:9876
  producer:
    group: test_user

mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: false

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      address:
      appname: xxl-job-executor-sample
      ip: 192.168.65.2
      port: 9999
      logpath: /home/ahua/workspace/java/demo/middle_ware/xxl-job/executorlog
      logretentiondays: 30
